DROP POLICY rls_ws_select ON deliverables;
DROP POLICY rls_ws_update ON deliverables;
DROP POLICY rls_ws_insert ON deliverables;
DROP POLICY rls_ws_delete ON deliverables;
CREATE POLICY rls_ws_select ON deliverables FOR SELECT USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text));
CREATE POLICY rls_ws_update ON deliverables FOR UPDATE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text)) WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_insert ON deliverables FOR INSERT WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_delete ON deliverables FOR DELETE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
DROP POLICY rls_ws_select ON execution_decisions;
DROP POLICY rls_ws_update ON execution_decisions;
DROP POLICY rls_ws_insert ON execution_decisions;
DROP POLICY rls_ws_delete ON execution_decisions;
CREATE POLICY rls_ws_select ON execution_decisions FOR SELECT USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text));
CREATE POLICY rls_ws_update ON execution_decisions FOR UPDATE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text)) WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_insert ON execution_decisions FOR INSERT WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_delete ON execution_decisions FOR DELETE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
DROP POLICY rls_ws_select ON execution_runs;
DROP POLICY rls_ws_update ON execution_runs;
DROP POLICY rls_ws_insert ON execution_runs;
DROP POLICY rls_ws_delete ON execution_runs;
CREATE POLICY rls_ws_select ON execution_runs FOR SELECT USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text));
CREATE POLICY rls_ws_update ON execution_runs FOR UPDATE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text)) WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_insert ON execution_runs FOR INSERT WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_delete ON execution_runs FOR DELETE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
DROP POLICY rls_ws_select ON products;
DROP POLICY rls_ws_update ON products;
DROP POLICY rls_ws_insert ON products;
DROP POLICY rls_ws_delete ON products;
CREATE POLICY rls_ws_select ON products FOR SELECT USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text));
CREATE POLICY rls_ws_update ON products FOR UPDATE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text)) WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_insert ON products FOR INSERT WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_delete ON products FOR DELETE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
DROP POLICY rls_ws_select ON requests;
DROP POLICY rls_ws_update ON requests;
DROP POLICY rls_ws_insert ON requests;
DROP POLICY rls_ws_delete ON requests;
CREATE POLICY rls_ws_select ON requests FOR SELECT USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text));
CREATE POLICY rls_ws_update ON requests FOR UPDATE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text)) WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_insert ON requests FOR INSERT WITH CHECK (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_delete ON requests FOR DELETE USING (((workspace_id)::text = current_setting('app.current_workspace_id'::text, true)));
DROP POLICY rls_ws_select ON workspaces;
DROP POLICY rls_ws_update ON workspaces;
DROP POLICY rls_ws_insert ON workspaces;
DROP POLICY rls_ws_delete ON workspaces;
CREATE POLICY rls_ws_select ON workspaces FOR SELECT USING (((id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text));
CREATE POLICY rls_ws_update ON workspaces FOR UPDATE USING (((id)::text = current_setting('app.current_workspace_id'::text, true)) OR (current_setting('app.current_workspace_id'::text, true) = '*'::text)) WITH CHECK (((id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_insert ON workspaces FOR INSERT WITH CHECK (((id)::text = current_setting('app.current_workspace_id'::text, true)));
CREATE POLICY rls_ws_delete ON workspaces FOR DELETE USING (((id)::text = current_setting('app.current_workspace_id'::text, true)));
